import './vue-prototype'
import './interceptors'
import './global'
import './err-img'
import './order-pay'
import './date-formatter'
import './filters'
import './rem'
// import './fastclick'
